In [1]:
import numpy as np

In [41]:
x = np.array([1, 2, 3, 4, 5])
N = 5
print(len(x))
np.vander(x, N, increasing = False)


5


array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

In [57]:
def vanderfn(arr1, num = None, increasing = False):
    num = len(arr1) if num is None else num
    arr2 = np.array([x**(num-1-i) for i in range(num)])
    arr2 = np.transpose(arr2)
    print(type(arr2))
    return arr2
    
    #print(arr2.transpose())

In [58]:
x = np.array([1, 2, 3, 4, 5])
print(vanderfn(x))

<class 'numpy.ndarray'>
[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]
